version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
